services:
  - type: web
    name: django-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn tonprojet.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tonprojet.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString

databases:
  - name: django-db
    plan: free
