# Generated by Django 5.1.6 on 2025-03-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_categoryaccommodation_alter_accommodation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryaccommodation',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
