# Generated by Django 5.1.4 on 2025-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_alter_accommodation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Nombre maximum de personnes'),
        ),
    ]
