# Generated by Django 5.1.6 on 2025-03-20 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_alter_categoryaccommodation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=models.TextField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='room_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.roomtype'),
        ),
    ]
