# Generated by Django 5.1.6 on 2025-03-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_roomtype_alter_accommodation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='room_types',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
