# Generated by Django 5.1.6 on 2025-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_accommodation_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='room_types',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='room_types',
            field=models.ManyToManyField(blank=True, to='accommodations.roomtype'),
        ),
    ]
