# Generated by Django 5.1.6 on 2025-03-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0005_remove_accommodation_room_types_delete_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
    ]
