# Generated by Django 5.1.6 on 2025-02-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('entrance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourist_places/')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_places', to='regions.region')),
            ],
        ),
    ]
