# Generated by Django 5.1.6 on 2025-03-28 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_categoryaccommodation_roomtype_and_more'),
        ('activities', '0003_alter_activity_rating'),
        ('lodge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgeadmin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='lodgeadmin',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='lodge',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddConstraint(
            model_name='lodge',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('is_active', False), _connector='OR'), name='valid_lodge_status'),
        ),
        migrations.DeleteModel(
            name='LodgeAdmin',
        ),
    ]
