# Generated by Django 5.1.6 on 2025-04-11 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0005_remove_accommodation_room_types_and_more'),
        ('activities', '0004_alter_activity_id_alter_activitycategory_id_and_more'),
        ('lodge', '0004_alter_lodgeaccommodation_id_alter_lodgeactivity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='accommodations',
            field=models.ManyToManyField(related_name='lodges', through='lodge.LodgeAccommodation', to='accommodations.accommodation'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='activities',
            field=models.ManyToManyField(related_name='lodges', through='lodge.LodgeActivity', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='lodgeaccommodation',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_accommodations', to='accommodations.accommodation'),
        ),
        migrations.AlterField(
            model_name='lodgeaccommodation',
            name='lodge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_accommodations', to='lodge.lodge'),
        ),
        migrations.AlterField(
            model_name='lodgeactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_activities', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='lodgeactivity',
            name='lodge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_activities', to='lodge.lodge'),
        ),
    ]
