# Generated by Django 5.1.6 on 2025-03-25 05:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='transport/categories/')),
            ],
            options={
                'verbose_name_plural': 'Transport Categories',
            },
        ),
        migrations.AddField(
            model_name='transport',
            name='air_conditioned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='transport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='driver_languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transport/vehicles/'),
        ),
        migrations.AddField(
            model_name='transport',
            name='insurance_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='luggage_capacity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='transport',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='transport',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Disponible'), ('maintenance', 'En maintenance'), ('booked', 'Réservé'), ('inactive', 'Inactif')], default='available', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='wifi_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.transportcategory'),
        ),
        migrations.CreateModel(
            name='TransportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='transports.transport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('transport', 'user')},
            },
        ),
    ]
