# Generated by Django 5.1.6 on 2025-03-27 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitycategory_activity_age_restriction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
